<?php

namespace app\admin\controller;

use think\Controller;
use think\facade\Log;
use think\facade\Response;
use think\Request;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (!session('uid')) {
            if (\think\facade\Request::isAjax()) {
//                 Response::code(999)->send();
               die(json(['code' => 999, 'msg' => '登录状态已失效，请刷新网页后重新登陆'],200)->send());
                exit;
            } else {
                $this->redirect('login/index');
            }
        }
    }

}
